version: '2'

services:
  myqsl:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: semb
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

  logstash:
    image: logstash:7.14.1

  elasticsearch:
    image: elasticsearch:7.14.1
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
      image: kibana:7.14.1
      container_name: kib01
      ports:
        - 5601:5601
      environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
        ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      networks:
        - elastic

networks:
  elastic:
      driver: bridge

volumes:
  mysql_db:
    driver: local
  data:
      driver: local
