version: '3.7'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: semb
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

  elasticsearch:
    image: elasticsearch:7.14.1
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled:false
      - xpack.management.enabled:true
      - xpack.security.audit.enabled:true
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.audit.enabled=true
      - ELASTIC_PASSWORD=root
      - discovery.type=single-node
      - discovery.zen.ping.unicast.hosts=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9600:9600"
    expose:
      - "9200"

  kibana:
    container_name: kibana
    image: kibana:7.14.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=root
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.14.1
    depends_on:
      - mysql
      - elasticsearch
    volumes:
      - ./volumes/logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./volumes/logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./volumes/logstash/config/queries/:/usr/share/logstash/config/queries/

volumes:
  mysql_db:
    driver: local
  elasticsearch-data:
    driver: local
