version: '2'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: semb
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

volumes:
  mysql_db:
    driver: local
